### PR TITLE
 AweSnapper connectors fix

### PR DESCRIPTION
**Pull request by asdorian**

### CODE REVIEW

**Comment by tucaz** [comment]
@asdorian what is this for?

**Comment by tucaz** [comment]
@acauan, @asdorian told me this was necessary for Approach to work. How is this necessary? I think I have a working version of approach without it.

**Comment by acauan** [comment]
@tucaz, there were recent changes in `AweSnapper` and it depends on this method to correctly render 2d, 3d and create parts.

**Comment by tucaz** [comment]
@acauan can you make a quick test to make sure this is necessary?

I released a working version of approach last week without this and everything seemed to be OK. @asdorian just told me he tested without it and it seems fine, but can you please test it without this patch as well?

Thanks

**Comment by acauan** [comment]
@tucaz I just tested it here and it looks good also. I think we were trying to open a very old drawing.

**Comment by tucaz** [comment]
@acauan Im closing this then. Not merging it. Thanks

**Pull request closed without merging**
